apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: musamauet/tickets
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-service:27017/tickets'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
    - name: tickets
      port: 3000
      targetPort: 3000
      protocol: TCP